services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api-gateway:
    image: kong:3.9
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_DECLARATIVE_CONFIG: /kong/config.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows access to host services
    volumes:
      - ./docker/kong/config.yml:/kong/config.yml  # Custom Kong configuration
    ports:
      - "8000:8000"  # Kong proxy port
      - "8001:8001"  # Kong admin API port
      - "8002:8002"  # Kong admin GUI port
      - "8443:8443"  # Kong proxy SSL port (Https)
      - "8444:8444"  # Kong admin API SSL port (Https)

volumes:
  rabbitmq_data: