_format_version: '3.0'
_transform: true

services:
  - name: orders
    url: ${ORDERS_SERVICE_URL}
    protocol: http
    host: host.docker.internal
    port: 3000
    path: /
    routes:
      - name: api-orders
        protocols:
          - http
          - https
        paths:
          - /orders

  - name: invoices
    url: http://host.docker.internal:3001
    protocol: http
    host: host.docker.internal
    port: 3001
    path: /
    routes:
      - name: api-invoices
        protocols:
          - http
          - https
        paths:
          - /invoices

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - PUT
        - POST
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Api-Version
        - X-Requested-With
        - Authorization